pipeline:
  run-mongo-tests:
    image: node:8.2
    commands:
      - sleep 5
      - cd mongo-node8 && ./bin/run.sh && cd ../
    when:
      status: [ failure, success ]
      event: [pull_request]

  run-logger-tests:
    image: node:8.2
    commands:
      - cd logger && ./bin/run.sh && cd ../
    when:
      status: [ failure, success ]
      event: [ pull_request ]

  run-api-starter-tests:
    image: node:8.2
    commands:
      - cd koa-api-starter && ./bin/run.sh && cd ../
    when:
      status: [ failure, success ]
      event: [ pull_request ]

  run-koa-react-starter-tests:
    image: node:8.2
    commands:
      - cd koa-react-starter && ./bin/run.sh && cd ../
    when:
      status: [ failure, success ]
      event: [ pull_request ]

  run-pdf-service-tests:
    image: node:8.2
    commands:
      - cd pdf-service/client && ./bin/run.sh && cd ../../
      - cd pdf-service/server && ./bin/run.sh && cd ../../
    when:
      status: [ failure, success ]
      event: [ pull_request ]


  # publish-mongo-node8:
  #   image: plugins/npm
  #   secrets: [ npm_username, npm_password, npm_email ]
  #   access: public
  #   folder: ./mongo-node-8
  #   username: paralect
  #   email: an.orsich@gmail.com
  #   password:

services:
  mongo:
    image: mongo:3.4
branches: [ master, "*:master" ]
