pipeline:
  run-logger-tests:
    image: node:8.2
    commands:
      - cd common-logger && ./bin/run.sh && cd ../
    when:
      status: [ failure, success ]
      event: [ pull_request ]

services:
  mongo:
    image: mongo:3.4

branches: [ master, "*:master" ]
